<?php

namespace Database\Seeders;

use App\Models\Curso;
use App\Models\GrupoCurso;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CursosFutbolCostaSeeder extends Seeder
{
    public function run(): void
    {
        $cursos = [
            // Cursos de Fútbol Base
            [
                'nombre' => 'Fútbol Prebenjamín - Escuela Óscar Cevallos',
                'descripcion' => 'Iniciación al fútbol para niños de 4 a 6 años. Desarrollo de coordinación, motricidad y amor por el deporte.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Óscar Cevallos Mendoza',
                'email_representante' => 'oscar.cevallos@futbolcosta.com',
                'telefono_representante' => '0991234567',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 25,
                'cupo_actual' => 0,
                'precio' => 45.00,
                'grupos' => [
                    ['nombre' => 'Grupo A - Mañana', 'hora_inicio' => '08:00', 'hora_fin' => '09:00', 'dias_semana' => ['lunes', 'miércoles', 'viernes'], 'cupo_maximo' => 13, 'cupo_actual' => 0, 'estado' => 'activo'],
                    ['nombre' => 'Grupo B - Tarde', 'hora_inicio' => '15:00', 'hora_fin' => '16:00', 'dias_semana' => ['martes', 'jueves', 'sábado'], 'cupo_maximo' => 12, 'cupo_actual' => 0, 'estado' => 'activo'],
                ]
            ],
            [
                'nombre' => 'Fútbol Benjamín - Academia Galo Delgado',
                'descripcion' => 'Formación técnica para niños de 7 a 8 años. Pases, control de balón y primeros conceptos tácticos.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Galo Delgado Rodríguez',
                'email_representante' => 'galo.delgado@futbolcosta.com',
                'telefono_representante' => '0992345678',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 28,
                'cupo_actual' => 0,
                'precio' => 50.00,
                'grupos' => [
                    ['nombre' => 'Grupo A - Mañana', 'hora_inicio' => '08:30', 'hora_fin' => '09:30', 'dias_semana' => ['lunes', 'miércoles', 'viernes'], 'cupo_maximo' => 14, 'cupo_actual' => 0, 'estado' => 'activo'],
                    ['nombre' => 'Grupo B - Tarde', 'hora_inicio' => '15:30', 'hora_fin' => '16:30', 'dias_semana' => ['martes', 'jueves', 'sábado'], 'cupo_maximo' => 14, 'cupo_actual' => 0, 'estado' => 'activo'],
                ]
            ],
            [
                'nombre' => 'Fútbol Alevín - Escuela Julio Arizaga',
                'descripcion' => 'Formación técnica para niños de 9 a 10 años. Desarrollo de habilidades y conceptos tácticos.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Julio Arizaga Zambrano',
                'email_representante' => 'julio.arizaga@futbolcosta.com',
                'telefono_representante' => '0993456789',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 30,
                'cupo_actual' => 0,
                'precio' => 55.00,
            ],
            [
                'nombre' => 'Fútbol Infantil - Escuela Ramón Arias',
                'descripcion' => 'Formación integral para niños de 11 a 12 años. Técnica avanzada, táctica y competencia.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Ramón Arias Montoya',
                'email_representante' => 'ramon.arias@futbolcosta.com',
                'telefono_representante' => '0994567890',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 32,
                'cupo_actual' => 0,
                'precio' => 60.00,
            ],
            [
                'nombre' => 'Fútbol Cadete - Academia Víctor Pincay',
                'descripcion' => 'Preparación competitiva para jóvenes de 13 a 14 años. Desarrollo físico y mental para competencias.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Víctor Pincay Salinas',
                'email_representante' => 'victor.pincay@futbolcosta.com',
                'telefono_representante' => '0995678901',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 28,
                'cupo_actual' => 0,
                'precio' => 65.00,
            ],
            [
                'nombre' => 'Fútbol Juvenil - Cantera Efrén Reyes',
                'descripcion' => 'Entrenamiento de alto rendimiento para jóvenes de 15 a 17 años. Preparación para categorías superiores.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Efrén Reyes Vélez',
                'email_representante' => 'efren.reyes@futbolcosta.com',
                'telefono_representante' => '0996789012',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 25,
                'cupo_actual' => 0,
                'precio' => 70.00,
            ],

            // Cursos Especializados
            [
                'nombre' => 'Porteros Elite - Técnica Rigoberto Cedeño',
                'descripcion' => 'Especialización en técnica de portería. Atajadas, distribución y liderazgo defensivo.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Rigoberto Cedeño Flores',
                'email_representante' => 'rigoberto.cedeno@futbolcosta.com',
                'telefono_representante' => '0997890123',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 12,
                'cupo_actual' => 0,
                'precio' => 85.00,
            ],
            [
                'nombre' => 'Defensa Táctica - Escuela Aurelio Rodríguez',
                'descripcion' => 'Especialización defensiva. Marcaje, cobertura y anticipación táctica.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Aurelio Rodríguez Sánchez',
                'email_representante' => 'aurelio.rodriguez@futbolcosta.com',
                'telefono_representante' => '0998901234',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 18,
                'cupo_actual' => 0,
                'precio' => 75.00,
            ],
            [
                'nombre' => 'Mediocampo Creativo - Academia Fausto Gruezo',
                'descripcion' => 'Desarrollo de creatividad en el mediocampo. Pases, visión de juego y control del ritmo.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Fausto Gruezo Moreno',
                'email_representante' => 'fausto.gruezo@futbolcosta.com',
                'telefono_representante' => '0999012345',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 16,
                'cupo_actual' => 0,
                'precio' => 80.00,
            ],
            [
                'nombre' => 'Delanteros Goleadores - Escuela Jaime Ayoví',
                'descripcion' => 'Especialización ofensiva. Remate, movimiento sin balón y efectividad goleadora.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Jaime Ayoví Quiñonez',
                'email_representante' => 'jaime.ayovi@futbolcosta.com',
                'telefono_representante' => '0990123456',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 14,
                'cupo_actual' => 0,
                'precio' => 80.00,
            ],

            // Cursos Vacacionales
            [
                'nombre' => 'Campamento Fútbol Verano - Dirección Wilman Vélez',
                'descripcion' => 'Campamento intensivo de fútbol durante vacaciones. Técnica, táctica y convivencia.',
                'fecha_inicio' => '2026-06-15',
                'fecha_fin' => '2026-07-31',
                'representante' => 'Wilman Vélez Ponce',
                'email_representante' => 'wilman.velez@futbolcosta.com',
                'telefono_representante' => '0991234568',
                'tipo' => 'vacacional',
                'estado' => 'activo',
                'cupo_maximo' => 40,
                'cupo_actual' => 0,
                'precio' => 120.00,
            ],
            [
                'nombre' => 'Torneo Fútbol Navideño - Coordinación Patricio Montero',
                'descripcion' => 'Preparación y participación en torneo navideño. Competencia y diversión.',
                'fecha_inicio' => '2026-11-15',
                'fecha_fin' => '2026-12-31',
                'representante' => 'Patricio Montero Salazar',
                'email_representante' => 'patricio.montero@futbolcosta.com',
                'telefono_representante' => '0992345679',
                'tipo' => 'vacacional',
                'estado' => 'activo',
                'cupo_maximo' => 35,
                'cupo_actual' => 0,
                'precio' => 100.00,
            ],

            // Cursos Temáticos
            [
                'nombre' => 'Fútbol Femenino - Academia Margarita Cevallos',
                'descripcion' => 'Formación especializada para futbolistas mujeres. Técnica, táctica y empoderamiento.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Margarita Cevallos Zambrano',
                'email_representante' => 'margarita.cevallos@futbolcosta.com',
                'telefono_representante' => '0993456790',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 26,
                'cupo_actual' => 0,
                'precio' => 60.00,
            ],
            [
                'nombre' => 'Fútbol Sala - Escuela Rodrigo Pincay',
                'descripcion' => 'Entrenamiento de fútbol sala. Técnica rápida, pases precisos y movimiento constante.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Rodrigo Pincay Flores',
                'email_representante' => 'rodrigo.pincay@futbolcosta.com',
                'telefono_representante' => '0994567891',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 20,
                'cupo_actual' => 0,
                'precio' => 55.00,
            ],
            [
                'nombre' => 'Fútbol Playa - Academia Costera Ángel Vera',
                'descripcion' => 'Especialización en fútbol playa. Técnica en arena, resistencia y diversión.',
                'fecha_inicio' => '2026-03-01',
                'fecha_fin' => '2026-05-31',
                'representante' => 'Ángel Vera Rodríguez',
                'email_representante' => 'angel.vera@futbolcosta.com',
                'telefono_representante' => '0995678902',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 24,
                'cupo_actual' => 0,
                'precio' => 50.00,
            ],
            [
                'nombre' => 'Futsal Competitivo - Cantera Ismael Sánchez',
                'descripcion' => 'Preparación competitiva en futsal. Estrategia, velocidad y precisión.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Ismael Sánchez Montoya',
                'email_representante' => 'ismael.sanchez@futbolcosta.com',
                'telefono_representante' => '0996789013',
                'tipo' => 'regular',
                'estado' => 'activo',
                'cupo_maximo' => 18,
                'cupo_actual' => 0,
                'precio' => 65.00,
            ],

            // Cursos Avanzados
            [
                'nombre' => 'Preparación Física Futbolística - Dirección Gonzalo Pincay',
                'descripcion' => 'Acondicionamiento físico específico para futbolistas. Fuerza, velocidad y resistencia.',
                'fecha_inicio' => '2026-02-01',
                'fecha_fin' => '2026-04-30',
                'representante' => 'Gonzalo Pincay Vélez',
                'email_representante' => 'gonzalo.pincay@futbolcosta.com',
                'telefono_representante' => '0997890124',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 22,
                'cupo_actual' => 0,
                'precio' => 75.00,
            ],
            [
                'nombre' => 'Psicología Deportiva en Fútbol - Coordinación Hernán Cedeño',
                'descripcion' => 'Desarrollo mental y emocional para futbolistas. Concentración, confianza y manejo de presión.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Hernán Cedeño Rodríguez',
                'email_representante' => 'hernan.cedeno@futbolcosta.com',
                'telefono_representante' => '0998901235',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 20,
                'cupo_actual' => 0,
                'precio' => 70.00,
            ],
            [
                'nombre' => 'Análisis Táctico Avanzado - Escuela Silvio Flores',
                'descripcion' => 'Estudio profundo de sistemas tácticos. Análisis de rivales y estrategia de juego.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Silvio Flores Montoya',
                'email_representante' => 'silvio.flores@futbolcosta.com',
                'telefono_representante' => '0999012346',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 16,
                'cupo_actual' => 0,
                'precio' => 85.00,
            ],
            [
                'nombre' => 'Entrenamiento de Porteros Avanzado - Academia Roque Pincay',
                'descripcion' => 'Especialización avanzada en portería. Técnica de pies, distribución y liderazgo.',
                'fecha_inicio' => '2026-02-15',
                'fecha_fin' => '2026-05-15',
                'representante' => 'Roque Pincay Salinas',
                'email_representante' => 'roque.pincay@futbolcosta.com',
                'telefono_representante' => '0990123457',
                'tipo' => 'especial',
                'estado' => 'activo',
                'cupo_maximo' => 10,
                'cupo_actual' => 0,
                'precio' => 95.00,
            ],
        ];

        foreach ($cursos as $curso) {
            $grupos = $curso['grupos'] ?? [];
            unset($curso['grupos']);
            
            $cursoCreado = Curso::create([
                ...$curso,
                'slug' => Str::slug($curso['nombre']),
            ]);

            // Crear los grupos asociados al curso
            foreach ($grupos as $grupo) {
                GrupoCurso::create([
                    'id_curso' => $cursoCreado->id_curso,
                    'nombre' => $grupo['nombre'],
                    'hora_inicio' => $grupo['hora_inicio'],
                    'hora_fin' => $grupo['hora_fin'],
                    'dias_semana' => $grupo['dias_semana'],
                    'cupo_maximo' => $grupo['cupo_maximo'] ?? 15,
                    'cupo_actual' => $grupo['cupo_actual'] ?? 0,
                    'estado' => $grupo['estado'] ?? 'activo',
                ]);
            }
        }
    }
}
